name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint(flake8, isort)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      
      - name: Run flake8
        run: flake8 .
      
      - name: Run isort
        run: isort . --check-only --diff

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: src.settings
          SECRET_KEY: test-secret-key
      