# Generated by Django 5.2.8 on 2025-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepart',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
